### ISSUE TITLE
connect() after disconnect() will fail

### ISSUE THREAD

**Issue by nrako** [otalk/stanza.io#101]
The following code should give a reproductible test case.

```javascript
import Stanza from 'stanza.io';

var client = Stanza.createClient({
  wsURL: 'ws://localhost:5280/ws',
  transport: 'websocket'
});

var creds = {
  jid: 'user@localhost',
  password: 'password'
};

client.once('auth:success', () => {
  client.on('auth:failed', (event) => {
    console.error('WTF');
  })
  client.once('disconnected', () => {
    client.connect(creds);
  });
  client.disconnect();
});

client.connect(creds);
```

It's because of a cache mechanism in [sasl.js](https://github.com/otalk/stanza.io/blob/master/lib/plugins/sasl.js#L47) which alter `config.credentials` and isn't cleared up after a disconnect.

Therefore [sasl-scram-sha module](https://github.com/legastero/js-sasl-scram-sha-1/blob/master/index.js#L67) end up using the wrong `clientKey` and `serverKey`.

**Comment by legastero** [comment]
The SCRAM-SHA-1 module has been updated to only use the cached credentials if the cached salt matches the salt provided by the server for the current auth attempt.

**Comment by nrako** [comment]
:+1: Thanks, just tested and it works like a charm! :sparkles:
