### ISSUE TITLE
Error with digest-md5 auth

### ISSUE THREAD

**Issue by ForNeVeR** [otalk/stanza.io#105]
I could not connect to jabber.ru server with `digest-md5` with the following snippet:

```js
var XMPP = require('stanza.io');
var client = XMPP.createClient({
    jid: jid,
    password: password,
    wsURL: 'ws://jabber.ru/ws',
    transports: ['websocket'],
    sasl: 'digest-md5'
});
client.connect();
```

It throws an error:

```
Uncaught TypeError: must start with number, buffer, array or string
fromObject @ client.js:225
Buffer @ client.js:195
(anonymous function) @ client.js:8471
Client.getCredentials @ client.js:6097
(anonymous function) @ client.js:8465
WildEmitter.emit @ client.js:35256
(anonymous function) @ client.js:5887
WildEmitter.emit @ client.js:35256
(anonymous function) @ client.js:6108
WildEmitter.emit @ client.js:35268
(anonymous function) @ client.js:9301
WildEmitter.emit @ client.js:35256
WSConnection.connect.self.conn.onmessage @ client.js:9331
```

(I'm using the latest Chrome browser.)

I've traced it down to [this js-sasl-digest-md5 line](https://github.com/legastero/js-sasl-digest-md5/blob/master/index.js#L38).

The server sends two challenges, the second contains `rspauth`. [This line](https://github.com/legastero/js-sasl-digest-md5/blob/master/index.js#L120) does `this._completed = true;`, after that [the `response` function returns `undefined`](https://github.com/legastero/js-sasl-digest-md5/blob/master/index.js#L38), and [that line](https://github.com/otalk/stanza.io/blob/master/lib/plugins/sasl.js#L38) tries to convert that `undefined` to a `Buffer` (and it does not succeed).

I'm not getting what's wrong here and how could I fix that error. Can anyone help? I am ready to test any proposed solution and contribute.

**Comment by legastero** [comment]
Minor patch has been published that should resolve this.

https://github.com/otalk/stanza.io/commit/20416da8d932d4aa45619e81cd6305e9710fb014

**Comment by ForNeVeR** [comment]
You guys are awesome! I'll check that tomorrow, thank you.

**Comment by ForNeVeR** [comment]
I've verified, everything works flawlessly now.
