### ISSUE TITLE
Question: How to use createDataChannel with stanza.io 7.3?

### ISSUE THREAD

**Issue by MaryLeland** [otalk/stanza.io#107]
Since upgrading from stanza.io version 6.3 to 7.3, We are having a problem adding a WebRTC datachannel to an existing WebRTC audio session.  Now that JXT has been split out of stanza.io, we are unsure what to use instead of the stanza.io 6.3 functions jxt.define, jingle.registerDescription, and jxt.extend.

Here are more details on what previously worked and the problem we have now:

What previously worked:
// Step 1, Define  content description for the datachannel:
var XMPP = require('stanza.io');
var MyData = XMPP.jxt.define({
    name: '_datachannel',
    namespace: 'http://dummy.com/protocol/mydata',
    element: 'description',
    fields: {
        descType: {
            value: 'datachannel'
        }
    }
});
XMPP.jingle.registerDescription(MyData);
XMPP.jxt.extend(XMPP.jingle.Content, MyData);

// Step 2. Get an XMPP client, where opts are filled out appropriately
var XMPP = require('stanza.io');
var client = XMPP.createClient({
            jid: opts.jid,
            password: opts.password,
            wsURL: opts.wsURL,
            transport: opts.transport || 'old-websocket',
            useStreamManagement: false
        });

// Step 3. On the initiator: After both initiator and receiver have joined the XMPP room, and the initiator has allowed use of the microphone, and the initiator has an audioStream:
var jingle = client.jingle;
var audioSession = jingle.createMediaSession(this.id);
audioSession.addStream(audioStream);
var channel = audioSession.pc.createDataChannel('mydata', {
                ordered: true,
                reliable: true
            });
channel.onopen = function () {
    console.log('Data Channel Open');
};
audioSession.start({
                mandatory: {
                    OfferToReceiveVideo: false,
                    OfferToReceiveAudio: true
                }
            });

Problem:
Step 1 no longer works because JXT has been split out of stanza.io.
Without a replacement for Step 1, as soon as the inititator does Step 3, the receiver gets an error:
"Uncaught TypeError: Cannot read property 'payloads' of undefined"
at line 39: 
    var payloads = desc.payloads || [];
of node_modules/jingle/node_modules/jingle-media-session/node_modules/rtcpeerconnection/node_modules/sdp-jingle-json/lib/tosdp.js
The initiator's channel.onopen is never called, and the data channel is never established.

**Comment by legastero** [comment]
We can replace the old Step 1 by making a new file that will contain the new Jingle registration process like so:
```js
// Step 1: Save this as 'helpers/jingle-definitions.js'
module.exports  = function (client, JXT) {

    var CustomDatachannel = JXT.define({
        name: '_datachannel',
        namespace: 'http://example.com/protocol/mydata',
        element: 'description',
        tags: [ 'jingle-description' ],
        fields: {
            descType: { value: 'datachannel' },
        }   
    }); 

    JXT.withDefinition('content', 'urn:xmpp:jingle:1', function (Content) {
        JXT.extend(Content, CustomDatachannel);
    }); 
}
```

Then, when the client is created, we load that file as a plugin:

```js
var XMPP = require('stanza.io');
var client = XMPP.createClient({
    jid: '...',
    password: '...'
});
client.use(require('../helpers/jingle-definitions'));
```

**Comment by stpeter** [comment]
Hi @MaryLeland did that approach work for you?

**Comment by rhashimoto** [comment]
The suggested solution worked for me, except that I needed to change `descType` to `applicationType` to get it delivered to my `prepareSession()` function.
