### ISSUE TITLE
Stanzas between stanza.io (client) and XMPP server during a video call

### ISSUE THREAD

**Issue by wmfairuz** [otalk/stanza.io#115]
Hi,

If I understand correctly even though the connection for the video call is peer to peer. Stanza.io still need to communicate to the XMPP server (e.g Prosody) to exchange some more messages / stanzas? If this is true, what kind of data / stanza that we talk about? 

Alos, how frequent and how big will these messages / stanzas be? 

Any hint and help is mostly appreciated.

**Comment by fippo** [comment]
right. See http://www.html5rocks.com/en/tutorials/webrtc/basics/#toc-signaling -- xmpp (and jingle) is used for signaling. Typically that means about 50 stanzas (one session-initiate, a session-accept and lots of transport-info) in each direction at the start of the session.

Easiest way to observe this is to try a call using http://legastero.github.io/jingle-interop-demos/stanzaio/

**Comment by wmfairuz** [comment]
Thanks!
Yes after testing with above demo, I do see around 120 stanza for both directions logged in the console. From that, I just calculate the number of characters of the stanza to estimate its size.
