### ISSUE TITLE
Build fails on node v5.1.0

### ISSUE THREAD

**Issue by gentlecat** [otalk/stanza.io#117]
Build fails on node v5.1.0 because of some issues in *node-stringprep* module. First it gives this warning:

    npm WARN engine node-stringprep@0.7.3: wanted: {"node":">=0.8 <=0.12"} (current: {"node":"5.1.0","npm":"3.3.12"})

and then fails completely: https://gist.github.com/anonymous/d9ba8c8ac9dbde110ad8.

Looks similar to this issue: https://github.com/node-xmpp/node-stringprep/issues/75.

**Comment by legastero** [comment]
I've made node-stringprep an optional dependency, and added fallbacks for when the module is not there at all. So this should be resolved now. Re-open if this still occurs after doing a fresh npm install.
