### ISSUE TITLE
TypeError: ltx.Element is not a function

### ISSUE THREAD

**Issue by vganapathy-lifesize** [otalk/stanza.io#119]
On invoking connect on the client object I get an exception most likely emanating from jxt/lib/helpers.js. I tried this with stanza.io versions 7.3.4 and 7.3.6. I am getting this in either case. Have you encountered such an issue? If so whats the way out?

**Comment by vganapathy-lifesize** [comment]
Could it be because of the latest ltx 2.x version? Not sure if this link in https://github.com/otalk/jxt/issues/8 is of any help here?

**Comment by legastero** [comment]
This is looking like a browserify issue where the ltx module is just an empty object.

No idea yet why this has started happening, still investigating.

**Comment by legastero** [comment]
Still not sure what the fundamental cause was here, but doing the upgrade to use ltx 2 seems to do the trick.

**Comment by legastero** [comment]
Published jxt@3.0.5 that resolves this. Re-open if you still have problems when using that version.

**Comment by vganapathy-lifesize** [comment]
Awesome! That does the trick! Thank you. It was real quick.
