### ISSUE TITLE
Properly ends a video call

### ISSUE THREAD

**Issue by wmfairuz** [otalk/stanza.io#122]
Hi,

How to properly end a video call? Right now what I did essentially is to just do `FOO.session.end()`
 where `FOO.session` comes from either:

```
client.on('jingle:incoming', function(session) {
    FOO.session = session;
    ...
}
```

or
```
FOO.session = client.jingle.createMediaSession(jid);
```

The problem is right now to be able to re-initiate a new call after a call is ended, I need to restart the application. Is there any other things to clean like streams or localMedia objects.

Thanks

**Comment by xdumaine** [comment]
You should end all localMedia stream tracks, if you plan to close the video UI. You'd only leave the media tracks active if you want to reuse them right away. Can you elaborate on "I need to restart the application"? it sounds like you have an error, which would be helpful in solving your problem.

**Comment by wmfairuz** [comment]
@xdumaine thanks! After some checking, apparently ending the session and all media tracks are enough.
