### ISSUE TITLE
list muc rooms 

### ISSUE THREAD

**Issue by denkomanceski** [otalk/stanza.io#126]
I am trying so hard to find a way to list all the rooms that are available for joining on my domain (example: 'conference.xxxx' but I cannot find documentation anywhere.. I tried most of the API in the Api Reference and I am not able to fetch them. I moved from strophejs to stanza.io (strophe had listRooms and I cant find the alternative here).
Also when I try to fetch chat history:
```
this.client.getHistorySearchForm(user.jid.bare, (data, err) => {
                        console.log(data, err, "History");
                    })
```
 I am getting an error which contains this:
`
by: JID
code: "405"
condition: "not-allowed"
lang: "en"
type: "cancel"
`
The server is configured with mam which I also managed to make it work with strophe. Can someone enlighten me on this please?

**Comment by denkomanceski** [comment]
I went through the code and I found a way to fetch the messages:
` this.client.searchHistory({
                    jid: 'xyz@domain',
                    with: 'asd@domain'
                }`
but I cannot add options to fetch the last X number of messages

**Comment by sarumjanuch** [comment]
client.getDiscoItems('muc.demo.local','',function(err,res){console.log(res); console.log(err)})

**Comment by denkomanceski** [comment]
perfect, thanks a lot. Do you maybe know how can i fetch the last 50 messages lets say from chat history ? the server is already configured to use mam

**Comment by sarumjanuch** [comment]
client.searchHistory({with:'jid@demo.local', rsm: {max: 50, before: true} },function(err, res){console.log(res)})

**Comment by denkomanceski** [comment]
Thanks a lot

**Comment by himanshusehgal** [comment]
client.getDiscoItems require 3 parametrs i.e. jid, node and cb.
Please tell me what to fill in these fields if i am running a MongooseIM server on , localhost and i want to fetch all the muc groups occupied by the jid : sandy@localhost
My XMPP domain name is also localhost.
