### ISSUE TITLE
Q: How can I get initial presence of all rosters?

### ISSUE THREAD

**Issue by thesabbir** [otalk/stanza.io#129]
I get presence status when 'presence' event fires 
```es6
client.on('presence', x => console.log(x));
```

but with

```es6
client.getRoster().then( rosters => console.log(rosters))
```
I do not get presence status/data. How can I get the presence status of all my rosters?

Thanks

**Comment by legastero** [comment]
You've got the right approach with the `client.on('presence', ...)` handler. That's the only way to get presence information in XMPP.

If you want to be sure that you've got your contact list before you start receiving presence, you can do it like this:

```js
client.on('session:started', function () {
    client.getRoster(function () {
        client.sendPresence();
    })
});
```

You will start receiving presence updates once you send your initial presence.
