### ISSUE TITLE
Filetransfer with Stanza

### ISSUE THREAD

**Issue by rikuhen** [otalk/stanza.io#130]
What is the best way to send and receive files trough stanza.io? help please :(

**Comment by rikuhen** [comment]
No one can help me? :c

**Comment by sarumjanuch** [comment]
use jingle file transfer.

**Comment by sarumjanuch** [comment]
http://legastero.github.io/jingle-interop-demos/stanzaio/

**Comment by rikuhen** [comment]
@sarumjanuch Thanks for your answer. I tried to use jingle file transfer but i receive error code 503 service unavailable

**Comment by sarumjanuch** [comment]
I have just tested jingle-interop-demos, and i am able to transfer files. Make sure you are using full jid with resource (id@domain/resource) to send file.

**Comment by rikuhen** [comment]
:o now understand! cool thanks!!

**Comment by rikuhen** [comment]
well, i need communicate with spark app and this uses stanzas (or other form).
do u know about other forms to send files?

**Comment by rikuhen** [comment]
now, i know what i need [XEP-0096: SI File Transfer](http://xmpp.org/extensions/xep-0096.html) is it possible?

**Comment by patelvanita360** [comment]
Hello @sarumjanuch , 

Using following demo i could not able to start Video Session, I able to transfer file using this. 
http://legastero.github.io/jingle-interop-demos/stanzaio/

**Comment by devsiodedra** [comment]
Not able to send file with jingle. 

getting code: "503", condition: "service-unavailable",text: "No module is handling this query"

my code for file transfer is :

var sess = client.jingle.createFileTransferSession(jid);
 sess.start(file);

// file is selected file object
// jid is receiver'sfull JID
