### ISSUE TITLE
ICE servers (TURN and STUN)

### ISSUE THREAD

**Issue by wmfairuz** [otalk/stanza.io#131]
When the server returns a set of STUN/TURN server list for the client to use, can we know exactly which server is used and for a particular server whether STUN or TURN feature that has been used?

Thanks

**Comment by fippo** [comment]
using the getStats API. See e.g. https://webrtc.github.io/samples/src/content/peerconnection/restart-ice/ as well as some of the other samples there.

**Comment by wmfairuz** [comment]
@fippo thanks for the link. Really appreciate it

**Comment by wmfairuz** [comment]
From Stanza library point of view, what should I replace peer with? I tried with client.peer but have no luck
