### ISSUE TITLE
Message Delivery Receipts

### ISSUE THREAD

**Issue by denkomanceski** [otalk/stanza.io#133]
I want to implement this feature to my app and I can see that Stanza supports this but I cant find anywhere any examples or how to use this. Can someone help me and send an example of this standard ? I will do my best to document it after

**Comment by sarumjanuch** [comment]
To request receipt:
```
            client.sendMessage({
                id: id,
                to: to,
                body: body,
                requestReceipt: true,
                type: 'chat'
            });
```
And handler to catch all responses:
`client.on('receipt', function(msg) {console.log(msg)});`

Stanza.io will automatically response to receipts requests.

**Comment by jlibrun22** [comment]
What if I want to control when I send a receipt... I have a situation where my websocket is open and the client will receive the messages, but I only want to send a message ack, when the messages are displayed on the users screen. If they are on a different page on the app, I don't want stanza to automatically send message received.
