### ISSUE TITLE
stream management reconnect

### ISSUE THREAD

**Issue by denkomanceski** [otalk/stanza.io#135]
What is the best way to do the following: sometime the client is getting disconnected (lets say his network went down) and I would like the app to try do "soft reconnect" so everything will be preserved (the resource, etc..). I tried using stream management and keepalive for this and to test it I turn off my network adapter -> the disconnect event listener got called which is great, but than after I reconnected the network, nothing is happening. I am not receiving any stanzas from the server and the client is not trying to reconnect to the server. Any idea how to solve this ? 

I am on ejabberd and stream management is enabled there as well. 
I expect stream:management:resume to be called but it isnt. Also maybe I can setup a timer on the disconnect event and try reconnect but what is the best way to trigger reconnect (client.connect() ?)

Any help would be appreciated

**Comment by legastero** [comment]
You'll need to call `client.connect()` again. That's left for you to do instead of stanza.io doing it directly so that you can have control over the timers and indicate the remaining time in your UI.

**Comment by denkomanceski** [comment]
Thanks

**Comment by DaveLombardo** [comment]
Hi guys, 
just a quick question here

should we call a `client.connect()` method with an empty list of arguments or we also can call it with the same opts param?

I mean is there any difference in these 2 calls - with and without opts ? or it's completely the same in this case?
