### ISSUE TITLE
Unable to get messages from history

### ISSUE THREAD

**Issue by thesabbir** [otalk/stanza.io#139]
My code:
```js
client.searchHistory({
with:'26@example.com',
   rsm: {
   max: 10,
   before: true
   }
 })
```

I get:
![](http://i.imgur.com/Hdz1DdD.png)

No message or body :confused: Even inside forwarded object.

But in log I can see raw xml:
![](http://i.imgur.com/ckexHPN.png)

**Comment by legastero** [comment]
In that raw log, there is:

```xml
<message xmlns="" ...
```

That missing namespace is what is causing the problem. Which server are you using for MAM?

**Comment by thesabbir** [comment]
openfire

**Comment by thesabbir** [comment]
I think it's a bug of MAM plugin of opefire.
@legastero I would appreciate toward a direction for workarounds to get going until they fix it.

**Comment by Ghost-cruiser** [comment]
Hi,
I'm currently facing the same issue, but I am not sure the problem comes from openfire and its plugin, since in the admin console, you can access the messages.
If you find a workaround or how to solve this, thank you in advance for letting me know!

**Comment by thesabbir** [comment]
Still haven't figured this out yet 😞 
@Ghost-cruiser what is your openfire version?

**Comment by thesabbir** [comment]
Might be this igniterealtime/Openfire#544

**Comment by Ghost-cruiser** [comment]
I'm using Openfire 4.0.2 with Monitor service 1.5.1 (I think the fix was integrated in this release)

**Comment by thesabbir** [comment]
Can you paste you raw incoming here?

**Comment by Ghost-cruiser** [comment]
<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" rid="9188867104" sid="7j0iw3tyc0"><iq xmlns="jabber:client" type="set" id="8a61999d-13b0-446e-9d85-4a5f2d5e41f3"><query xmlns="urn:xmpp:mam:0" queryid="8a61999d-13b0-446e-9d85-4a5f2d5e41f3"><set xmlns="http://jabber.org/protocol/rsm"><max>50</max><before/></set><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>urn:xmpp:mam:0</value></field><field var="with"/></x></query></iq></body>

**Comment by Ghost-cruiser** [comment]
Erf, sorry : "<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" rid="9188867104" sid="7j0iw3tyc0"><iq xmlns="jabber:client" type="set" id="8a61999d-13b0-446e-9d85-4a5f2d5e41f3"><query xmlns="urn:xmpp:mam:0" queryid="8a61999d-13b0-446e-9d85-4a5f2d5e41f3"><set xmlns="http://jabber.org/protocol/rsm"><max>50</max><before/></set><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>urn:xmpp:mam:0</value></field><field var="with"/></x></query></iq></body>"

**Comment by Ghost-cruiser** [comment]
![image](https://cloud.githubusercontent.com/assets/17065525/14607047/38696d7e-0580-11e6-94fa-59f02e91620f.png)

**Comment by thesabbir** [comment]
I think it's the search query.
Can you paste incoming? Like mine on the top?

**Comment by Ghost-cruiser** [comment]
Sorry, I'm a beginner (apprentice), is that what you're asking me? (intercepted with fiddler)
![image](https://cloud.githubusercontent.com/assets/17065525/14607622/8e63a094-0582-11e6-8f26-719faa21930c.png)

**Comment by thesabbir** [comment]
@Ghost-cruiser yes. Same issue. Namespace missing.

**Comment by guusdk** [comment]
This is a bug in Openfire's Monitoring plugin. We're tracking it in https://igniterealtime.org/issues/browse/OF-1132

I've submitted a fix in https://github.com/igniterealtime/Openfire/pull/582 which should be available in the upcoming 1.5.4 release of the Monitoring plugin.

**Comment by thesabbir** [comment]
@guusdk thanks 🎅 !

**Comment by guusdk** [comment]
Sure thing. Thanks for the debugging :)
