### ISSUE TITLE
MUC Invite

### ISSUE THREAD

**Issue by denkomanceski** [otalk/stanza.io#142]
Hi, I am struggling to find out how to use the muc invite functionality. ```directInvite``` works but I can only invite one user. How do I use the ```client.invite``` functionality to be able to invite more than one user at once. Also, what happens if the room is public, how to invite the roster (or how do they discover the newly added room). I see ```opts``` in the documentation but I dont know which ones to use. Of course I will document this after I am finished and make a pull request

Thanks in advance

**Comment by GerardoRobledo** [comment]
ok, so `opts` should be an array containing the list of users you want to invite.
like this:
`var opts =[{to="username@domain.com",to="username2@domain.com"}]`
`client.invite(room,opts)`

Hope this helps you.

**Comment by ravikantmishra** [comment]
I know its too late but this could be useful for others. Working for me.
```
var opts =[{to : ["user1@domain.com", "user2@domain.com"]}]
client.invite(room, opts)
```

**Comment by patelvanita360** [comment]
It's working but it just sends the invitation. Is there any way to auto join multiple members in the room OR how to handle invitation from other users?
