### ISSUE TITLE
Adding custom attribute to message stanza

### ISSUE THREAD

**Issue by FloraRai** [otalk/stanza.io#143]
Is it possible to add a custom attribute to message stanza using stanza.io ?
something like 

```
<message to="tom@example" id="273z4-567" type="chat" from="john@example"> 
<body>hi</body> 
**<messageAttribute xmlns="xmpp:example:messageAttribute"> 
<key>g8wO51C5kuvNNQ9Q</key> 
</messageAttribute> **
<request xmlns="urn:xmpp:receipts"/> 
</message> 
```

Thanks!!

**Comment by thesabbir** [comment]
Yes you can extend message.
```js
function customMessage(client, stanzas) {
    const NS = 'xmpp:example:messageAttribute';
    const messageAttribute = stanzas.define({
        name: 'messageAttribute',
        element: 'messageAttribute',
        namespace: NS,
        fields: {
            key: stanzas.utils.textSub(NS, 'event'),
        }
    });
    stanzas.withMessage((Message) => {
        stanzas.extend(Message, messageAttribute);
    });
}
client.use(customMessage);
client.sendMessage({
   to: "",
   body: "",
   messageAttribute: {
   key: ""
 }
});
```

For more: see #47

**Comment by legastero** [comment]
Thanks @thesabbir!

That's the correct approach. See also https://github.com/otalk/stanza.io/blob/master/docs/Create_Plugin.md

**Comment by FloraRai** [comment]
Thank you @thesabbir!

**Comment by gaurangkela** [comment]
@legastero and @thesabbir can you tell me how can i send multiple attribute such as name and contact number?

**Comment by itsazzad** [comment]
Add multiple fields @gaurangkela

**Comment by gaurangkela** [comment]
@itsazzad can you give me example ? i have opened [https://github.com/legastero/stanza.io/issues/247](issue). you can see how i have added multiple attribute and help me in this issue if you can.

**Comment by Alacho2** [comment]
Is this still valid today, or is the approach mentioned in "Creating Plugins" better?
I'd love to extend message
