### ISSUE TITLE
Send Message with custom parametr

### ISSUE THREAD

**Issue by ekiwookie** [otalk/stanza.io#144]
Hello

Can i send messages with custom parametr fields?

`<message to="14@192.168.2.45" type="chat" custom='param'>
<body>msg</body>
</message>`

**Comment by ekiwookie** [comment]
sorry, it is good for me:
https://github.com/otalk/stanza.io/issues/143

**Comment by fippo** [comment]
the spec actually forbid putting custom things on top of the stanza.
