### ISSUE TITLE
How to create a new JID accounts using stanza.io

### ISSUE THREAD

**Issue by metalaureate** [otalk/stanza.io#68]
Question: Is it possible to register new accounts using this API?

For example, http://node-xmpp.github.io/doc/nodexmppclient.html has a register:true option when creating the client which does that. I've floundering trying to figure out how to do it for stanz.io. Am I missing something?

**Comment by metalaureate** [comment]
@legastero is there a way to create a new XMPP account with stanza.io? I would like to remove my dependency on `node-xmpp-client` and standardize my app on stanza.io.

**Comment by legastero** [comment]
The building blocks to do it are there, but they aren't wired up to do in-band registration at the moment. They're there currently for dealing with registering with components & other services, not creating a brand new XMPP account.

Originally I purposefully left out in-band registration because it really shouldn't be used, due to spam problems that occur in the wild due to servers leaving in-band registration open, letting spammers create large amounts of accounts on demand from 'good' domains. It's best to just always use out-of-band registration to create accounts.

Or, if you just need lots of unique, temporary accounts, using SASL anonymous auth usually works great.


All of that said, I'll add in the hook to make in-band registration handleable.

**Comment by metalaureate** [comment]
It's totally great to get that architectural perspective. Thank you.

**Comment by M-A-D-A-R-A** [comment]
As all the same it is realized. What functions should I use?

**Comment by gencatz** [comment]
> The building blocks to do it are there, but they aren't wired up to do in-band registration at the moment. They're there currently for dealing with registering with components & other services, not creating a brand new XMPP account.
> 
> Originally I purposefully left out in-band registration because it really shouldn't be used, due to spam problems that occur in the wild due to servers leaving in-band registration open, letting spammers create large amounts of accounts on demand from 'good' domains. It's best to just always use out-of-band registration to create accounts.
> 
> Or, if you just need lots of unique, temporary accounts, using SASL anonymous auth usually works great.
> 
> All of that said, I'll add in the hook to make in-band registration handleable.

I think the demand huge for the support and why shouldn't the app developer decide to incorporate the registration or not? The library is great but this one essential feature is missing and I don't know how to proceed.. Now I have to use another library to do the in-band registration and it's a mess. Or at least you could provide a way how to build an xml stanza which is also a mess but at least a generic way.

**Comment by legastero** [comment]
> I think the demand huge for the support

I've now had 4 people ask me about this in 8 years, so 🤷. There just are better ways to do what people usually want in-band registration for (e.g. SASL anonymous, or custom server auth plugins).

> why shouldn't the app developer decide to incorporate the registration or not?

Sure. Everything needed is already there, so here's how an app can decide to allow it (with stanza@12):

```typescript
client.registerFeature('inbandRegistration', 50, async (features, done) => {
    // Using 50 ensures we run before SASL (100)

    // Really should do stuff like inspecting for form vs old fields
    // vs out-of-band, etc.
    // And those might need to get presented to the user somehow, while we
    // have stream setup paused to process this.
    //
    // Up to you how to do it, but `registration` here has the info you need.
    const registration = await client.getAccountInfo(client.config.server);
    console.log(registration);

    // !!! Blindly assuming here we're going to just need username/password,
    //     and that they've already been configured. 

    // Ensure we get username, password, etc, the same way that SASL auth does
    const credentials = await client.getCredentials();

    await client.updateAccount(undefined /* Registering a new account in-band */, {
        // Old style fields
        username: credentials.username,
        password: credentials.password,

        // Form style
        form: {
            fields: [
                {
                  name: 'FORM_TYPE',
                  type: 'hidden',
                  value: Stanza.Namespaces.NS_REGISTER
                },
                { name: 'username', value: credentials.username },
                { name: 'password', value: credentials.password }
            ]
        }
    });

    // Continue stream feature processing (SASL auth using the new account)
    done();
});
```

**Comment by gencatz** [comment]
> > I think the demand huge for the support
> 
> I've now had 4 people ask me about this in 8 years, so 🤷. There just are better ways to do what people usually want in-band registration for (e.g. SASL anonymous, or custom server auth plugins).
> 
> > why shouldn't the app developer decide to incorporate the registration or not?
> 
> Sure. Everything needed is already there, so here's how an app can decide to allow it (with stanza@12):
> 
> ```ts
> client.registerFeature('inbandRegistration', 50, async (features, done) => {
>     // Using 50 ensures we run before SASL (100)
> 
>     // Really should do stuff like inspecting for form vs old fields
>     // vs out-of-band, etc.
>     // And those might need to get presented to the user somehow, while we
>     // have stream setup paused to process this.
>     //
>     // Up to you how to do it, but `registration` here has the info you need.
>     const registration = await client.getAccountInfo(client.config.server);
>     console.log(registration);
> 
>     // !!! Blindly assuming here we're going to just need username/password,
>     //     and that they've already been configured. 
> 
>     // Ensure we get username, password, etc, the same way that SASL auth does
>     const credentials = await client.getCredentials();
> 
>     await client.updateAccount(undefined /* Registering a new account in-band */, {
>         // Old style fields
>         username: credentials.username,
>         password: credentials.password,
> 
>         // Form style
>         form: {
>             fields: [
>                 {
>                   name: 'FORM_TYPE',
>                   type: 'hidden',
>                   value: Stanza.Namespaces.NS_REGISTER
>                 },
>                 { name: 'username', value: credentials.username },
>                 { name: 'password', value: credentials.password }
>             ]
>         }
>     });
> 
>     // Continue stream feature processing (SASL auth using the new account)
>     done();
> });
> ```

Thanks but I'm not sure if I should a client with an anonymous connection to do the registration. It never stops at debugger. What I have so far is:

`
import * as stanza from 'stanza.io';

  this.client = stanza.createClient({
      username: this.username,
      password: this.password,
      sasl: "ANONYMOUS",
      transport: 'websocket',
      wsURL: 'ws://server_ip:7070/ws/'
    });

    this.client.registerFeature('inbandRegistration', 50, async (features, done) => {
      debugger;

      await this.client.updateAccount(undefined, {
        form: {
            fields: [
                {
                  name: 'FORM_TYPE',
                  type: 'hidden',
                  value: 'jabber:iq:register'
                },
                { name: 'username', value: this.username },
                { name: 'password', value: this.password }
            ]
        }
    });

     done();
    });

`
Can you help me here?
