### ISSUE TITLE
Broken for Prosody 0.9.7 (stream is undefined)

### ISSUE THREAD

**Issue by kdex** [otalk/stanza.io#70]
When downgrading to Prosody 0.9.7 (current stable) in the backend, I get this error:

    return f.emit("stream:end"),f.disconnect();n.lang||(n.lang=f.stream.lang
                                                                 ^^^^^^^^^^^
    Cannot read property 'lang' of undefined

**Comment by legastero** [comment]
This should be taken care of now in `7.0.6`
