### ISSUE TITLE
Rename *subText to *textSub

### ISSUE THREAD

**Issue by kdex** [otalk/stanza.io#73]
It seems that the JXT API has changed between 6.x and 7.x.
The JXT type functions in `client.stanzas.utils` mostly seem to resemble what can be seen [here](https://www.npmjs.com/package/jxt). There's a little irregularity in the naming: `*subText` should (according to all the other function names) be something like `*textSub`, so that it matches the predominantly used scheme given by other type functions, for instance, `boolSub`, `dateSub`, `enumSub` or `numberSub`.

This comprises:

`multiSubText` → `multiTextSub`
`subLangText` → `langTextSub`
`subText` → `textSub`

That is, unless there is a good reason for having two naming schemes or I'm missing out on something.
(Oh, and just out of interest: What is a "sub" anyway — a substitution?)

**Comment by legastero** [comment]
This would be an issue for https://github.com/otalk/jxt, but I agree.

`client.stanzas.utils` is just a JXT registry instance, so this will require bumping the major version for JXT first.

("sub" is just short for "sub-element")

**Comment by kdex** [comment]
I just updated to `7.0.6` and noticed that nothing broke for me. `stanzas.utils` now references **both** `textSub` and `subText`, `langTextSub` is not a property (but `subLangText` still is) and **both** `multiSubText` (old) and `multiTextSub` (new) are also properties. Did you mean to do this?
