### ISSUE TITLE
Can't create a persistent members-only muc room

### ISSUE THREAD

**Issue by metalaureate** [otalk/stanza.io#74]
Sorry if this is a dumb question / misses the point. Please help me understand the concepts if I am in error: I see `joinRoom`, which seems to create some sort of public room if none exists. I am trying to create members-only rooms ('Reserved rooms'?) with stanza.io but struggling to figure out a way to do it. I think the portion of the XEP I am trying to use stanza.io for is http://xmpp.org/extensions/xep-0045.html#createroom

**Comment by metalaureate** [comment]
Awesome! Thank you. I didn't see configureRoom() in the API docs. If I could impose upon you for one more thing: once the room is created, how would I use stanza.io to add a user to that room?

**Comment by legastero** [comment]
Sounds like you want:

```js
client.setRoomAffiliation('yourroom@conference.example.com', 
                          'theuser@example.com', 
                          'member');
                          // "reason for change",
                          // callbackFunction);
```

Where you can use `'member'`, `'admin'`, `'owner'`, `'none'`, or `'outcast'` for that third arg.

**Comment by metalaureate** [comment]
Ahhh, got it. Thank you. Thanks again for your project.

**Comment by khsrikanth89** [comment]
I have been trying to create a room using:
client.configureRoom('yourroom@conference.example.com', {
    fields: [
        { name: 'FORM_TYPE', value: 'http://jabber.org/protocol/muc#roomconfig' }, 
        { name: 'muc#roomconfig_persistentroom', value: '1'}
    ]
});

But it throws an Unhandled rejection Error: [object Object]
Any idea what might be causing it?
