### ISSUE TITLE
File Transfer demo using stanza.io

### ISSUE THREAD

**Issue by dhaval-vnc** [otalk/stanza.io#79]
Hello Devs, 

Do we have a demo of how to do the file transfer using stanza.io? I've seen that the file transfer support has been some commit where file transfer is reverted back to old version in the commit here https://github.com/otalk/stanza.io/commit/85b4df9ce47af847a4a2e9d87ff7eeea68f6eca6#diff-0859933e37ab8df1c60c8c433cf2af27

Could you please guide me to a wiki page or API reference for file transfer using stanza.io?

Thanks.

**Comment by legastero** [comment]
Here's a quick demo for it: http://code.gar.zone/?gist=8e0436e22e09ce74310c

Just open in two tabs and enter the same name when prompted in each.

**Comment by fippo** [comment]
See also https://github.com/legastero/jingle-interop-demos/tree/gh-pages/stanzaio

**Comment by dhaval-vnc** [comment]
Thank you guys. I'll check them out and implement next week. Will let you the outcome.

**Comment by dhaval-vnc** [comment]
Hello Guys, 

I've tried the demo but it give me an error on following line saying "Uncaught TypeError: Cannot read property 'receivedFile' of undefinedVM317:24696 224.WildEmitter.onVM319:12147 (anonymous function)". 

session.on('receivedFile', function (session, file, metadata) {

Looks like receivedFile callback is not supported.

**Comment by dhaval-vnc** [comment]
I am now using latest stanzaio.bundle.js. I am getting following error in Firefox now. In chrome it does not give any error. And file transfer does not work. 

TypeError: self.config.ice[ice.sdpMid] is undefine

**Comment by dhaval-vnc** [comment]
Looks like with Firefox it's not working. Only Chrome is supported. I started testing in Chrome only. 

And now getting following error. 
Invalid non-string/buffer chunk

**Comment by dhaval-vnc** [comment]
@legastero Which stanzaio.bundle.js are you using? I'd like to use the same and see if it leads to the same result or not. 

Besides, do you think I require to use STUN or TURN or ICE servers?

**Comment by dhaval-vnc** [comment]
![screenshot - monday 09 february 2015 - 07 04 38 ist](https://cloud.githubusercontent.com/assets/2663246/6107200/a0200592-b08e-11e4-8111-eaf9602ed9fc.png)

@legastero , I've reproduce the same issue in your example. Please have a look at the screenshot. To me it looks like a bug.

**Comment by dhaval-vnc** [comment]
It's basically a bug. I've checked that the validChunk function should check for type Uint8Array. And should allow it.

**Comment by fippo** [comment]
that looks like a bug in https://github.com/feross/drag-drop -- @feross: ping?

**Comment by dhaval-vnc** [comment]
@fippo I've already fixed the problem of "" and also I patched the stanzaio.bundle.js in order to allow Uint8Array by validChunk function. It's working perfect now. But looks like you guys have to change the implementation or something or either validChunk function of read_streams library of NodeJS should be changed to have Uint8Array check in validChunk.

**Comment by feross** [comment]
The `validChunk` error comes from the node.js streams implementation. It's checking that you're giving it either a string or a buffer. If you're using browserify (or something similar), everything should work fine. Browser buffers will pass the `Buffer.isBuffer` or `instanceof Buffer` checks internally.

@fippo `drag-drop` returns W3C File objects, not Buffers, so this issue seems unrelated.
