### ISSUE TITLE
Problem with new extension

### ISSUE THREAD

**Issue by zooldk** [otalk/stanza.io#80]
Hi,

I am implementing a new extension (the IOT stuff) and am having problems in serializing the correct stanzas.
I am using an old version of stanza.io so I know that I should be using the old stanzas.extend(stanza, myNewExtension); instead of the new api in version 7.

So basically what I am doing is this:

```javascript
var xep323 = function (client, stanzas) {
    var NS = 'urn:xmpp:iot:sensordata';
    var types = stanzas.utils;
    
    client.disco.addFeature(NS);
    
    var Req = stanzas.define({
        name: 'req',
        element: 'req',
        namespace: NS,
        fields: {
            seqnr: types.attribute('seqnr'),
            momentary: types.attribute('momentary')
        }
    });
    
    stanzas.extend(XMPP.Iq, Req);

    client.getData = function (jid, momentary, cb) {
        return this.sendIq({
            to: jid,
            type: 'get',
            seq: '1',
            momentary: momentary
        }, cb);        
    };
    
    client.on('urn:xmpp:iot:sensordata', function (iq) {
        if (iq.req) {
            console.log("GOT IQ for sensor", iq);
            client.emit('req', iq);
            //client.sendIq(iq.resultReply());
        }
    });
};
```
The output is an IQ stanza that is missing my <req ..> element, which should have been inside.

<iq from="slarsen@xxx/tigase-8" type="get" id="99bd4c92-8705-4439-be21-059d3a131667" to="testtest@xxx/testtest"/>

What am I missing?

**Comment by legastero** [comment]
Looks like your `getData()` function isn't building the query properly (not using  your defined `req`, nor `seqnr`):

```js
client.getData = function (jid, momentary, cb) {
    return this.sendIq({
        to: jid,
        type: 'get',
        req: {
            seqnr: '1',
            momentary: momentary
        }
    });
};
```

And for the iq handler, you'd want to use the event `iq:get:req` (because you named your substanza `req`):

```js
client.on('iq:get:req', function (iq) {
    console.log("GOT IQ for sensor", iq);
    client.emit('req', iq);
});
```

Also, be aware that in the conversion to JSON everything is now in the same "namespace", so you might want to use a more descriptive name than `req`.

**Comment by zooldk** [comment]
Cool, thanks Lance, it works!. I was staring my self blind and could see that I was missing the req element in my sendIq method. I have changed the emitting namespace as well into a more suitable one that matches the XEP.
