### ISSUE TITLE
Getting client instance

### ISSUE THREAD

**Issue by triniwiz** [otalk/stanza.io#83]
I'm using stanza.io to create a ionic app i was wondering is there anyway i can get an instance of the client when its already established 

im trying something like this

login: function (user) {

                var config = {
                    jid: user.username + '@myserver.com',
                    password: user.password,
                    transport: 'websocket',
                    wsURL: 'wss://myserver.com/xmpps-websocket',
                    useStreamManagement: true
                };
              
                SharedProperties.sharedData.client = XMPP.createClient(succ);

SharedProperties.sharedData.client.connect()

                

                        }
getContacts: function(){
var client = SharedProperties.sharedData.client;

client.getRoster(function(err,success){
if(success != null){
console.log(success)
}else{
console.log(error)
}
})

}

and after i login and try to run the get contacts function nothing runs or do i have to run the client.connect() function from the getContacts

**Comment by triniwiz** [comment]
ok i did some testing and i figured it out :smile:

**Comment by Gaurav-gs** [comment]
Hey... I am also looking for the same thing but no luck so far. i would really appreciate I you can share with me the approach to do the same..

Thanks..

**Comment by goors** [comment]
@triniwiz how did you resolve this?
