### ISSUE TITLE
XMPP.VERSION is wrong

### ISSUE THREAD

**Issue by kdex** [otalk/stanza.io#87]
`package.json` is versioned `7.0.7`, but `XMPP.VERSION` evaluates to `7.0.6` for the current build (fb3722f25a5484329a050b0fde2b68fe2df47085).

It looks as if you were updating two distinct version strings when bumping versions. Is there a way you could just parse the JSON from within stanza.io and use the version you find over there?

**Comment by legastero** [comment]
Now using https://github.com/webpro/versionify to make that automatic.
