### ISSUE TITLE
No way to destroy a room

### ISSUE THREAD

**Issue by metalaureate** [otalk/stanza.io#88]
How would I use stanza.io to destroy room?

You have a hook for the event, but I don't see a way to invoke it.

Thanks for any clarification you can provide about this.

**Comment by legastero** [comment]
Ah, good catch. I'll add `client.destroyRoom()` to make that easier.

In the meantime, you can do this now by using:

```js
client.sendIq({
    to: roomJID,
    type: 'set',
    mucOwner: {
        destroy: true // or { jid: alternateRoomJID, reason: 'because', password: 'letmeinthenewroom'}
    }
}, cb);
```

**Comment by metalaureate** [comment]
Great, thank you.
