### ISSUE TITLE
SSL BOSH endpoint does not appear to work

### ISSUE THREAD

**Issue by metalaureate** [otalk/stanza.io#93]
I'm troubleshooting switching my BOSH endpoint to SSL. I can connect fine over SSL with Pigin, as well as telnet, but stanza.io appears to hang.

```
      var client = XMPP.createClient({
            jid: from_JID,
            password: 'password',
            transport: 'bosh',
            boshURL: config.get('xmpp.bosh_url') // https://domain.com/http-bind

        });
```

Can I rule out stanza.io? Am I doing something wrong?

**Comment by legastero** [comment]
Is this in browser or node?

Is it a self-signed or any type of cert that would require accepting a security prompt?

Do you have CORS enabled?

**Comment by metalaureate** [comment]
node.js server-side. Standard cert. CORS enabled.

**Comment by metalaureate** [comment]
I have what appears to be the same problem with node-xmpp-client, which I use exclusively for prebinding.

**Comment by legastero** [comment]
Gut feeling is still for a cert validation issue. Does your server have its cert installed properly with cert + chain? Especially if using a CA with an intermediary cert.

**Comment by metalaureate** [comment]
I did that today. https://idelog.me Would you able to verify? I just followed the AWS Load balancer instructions... Don't know much about certs. :)

**Comment by legastero** [comment]
Yep, this is what node is giving:

     [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]

You've got two intermediary certs (Gandi Standard SSL CA 2, and USERTrust RSA Certificate Authority).

I'd check that you have those two included in your PEM bundle, and in the right order (your cert at the top, followed by Gandi, then USERTrust).

**Comment by metalaureate** [comment]
Awesome thank you - I do not.

**Comment by metalaureate** [comment]
That fixed it. Sorry to have bothered you with that. Thank you.
