### ISSUE TITLE
Namespace is always required but should not be

### ISSUE THREAD

**Issue by markr79** [otalk/stanza.io#94]
As per [rfc6120](http://xmpp.org/rfcs/rfc6120.html#streams-ns-content) :

>##### 4.8.2.  Content Namespace

>An entity MAY declare a "content namespace" as the default namespace for data sent over the stream (i.e., data other than elements qualified by the stream namespace). If so, (1) the content namespace MUST be other than the stream namespace, and (2) the content namespace MUST be the same for the initial stream and the response stream so that both streams are qualified consistently. The content namespace applies to all first-level child elements sent over the stream unless explicitly qualified by another namespace (i.e., the content namespace is the default namespace).

>Alternatively (i.e., instead of declaring the content namespace as the default namespace), an entity MAY explicitly qualify the namespace for each first-level child element of the stream, using so-called "prefix-free canonicalization". These two styles are shown in the following examples.

>When a content namespace is declared as the default namespace, in rough outline a stream will look something like the following.
```xml
<stream:stream
    from='juliet@im.example.com'
    to='im.example.com'
    version='1.0'
    xml:lang='en'
    xmlns='jabber:client'
    xmlns:stream='http://etherx.jabber.org/streams'>
  <message>
    <body>foo</body>
  </message>
</stream:stream>
```
>When a content namespace is not declared as the default namespace and so-called "prefix-free canonicalization" is used instead, in rough outline a stream will look something like the following.
```xml
<stream
    from='juliet@im.example.com'
    to='im.example.com'
    version='1.0'
    xml:lang='en'
    xmlns='http://etherx.jabber.org/streams'>
  <message xmlns='jabber:client'>
    <body>foo</body>
  </message>
</stream>
```
>Traditionally, most XMPP implementations have used the content-namespace-as-default-namespace style rather than the prefix-free canonicalization style for stream headers; however, both styles are acceptable since they are semantically equivalent.

Which means that depth 1 element might not have a namespace that causes exception in stanza.io's stanza parser.

Easy to reproduce with MongooseIM 1.4

**Comment by legastero** [comment]
If using WebSocket, then namespaces are required on every stanza (as per [RFC 7395](https://tools.ietf.org/html/rfc7395#section-3.3.3)).

However, if you know your server is sending `<stream:stream>` over WebSocket (as opposed to the `<open/>` and `<close/>` elements defined in RFC 7395), then you need to use the `old-websocket` transport.

**Comment by markr79** [comment]
@legastero thank you for clarification, that makes sense, closing the ticket.
